apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXMxMjM=
  url: amRiYzpwb3N0Z3Jlc3FsOi8vZGF0YWJhc2Utc2VydmljZTo1NDMyL2FjY29tbW9kYXRpb25iYXNlJQ==

#  url: amRiYzpwcm9zdGdyZXM6Ly9kYXRhYmFzZS1zZXJ2aWNlOjU0MzIvYWNjb21tb2RhdGlvbmJhc2U=

#  database: cG9zdGdyZXM=
#  username: cG9zdGdyZXM=
#  password: cG9zdGdyZXMxMjM=  # base64 encoded value of "password"
#  url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL2FjY29tbW9kYXRpb25iYXNl
