apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops
data:
  application.properties: |
    server.port=8080
    spring.datasource.url=jdbc:postgresql://database-service:5432/accommodationbase
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}

