apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: devops
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXMxMjM=
  url: amRiYzpwcm9zdGdyZXM6Ly9kYXRhYmFzZS1zZXJ2aWNlOjU0MzIvYWNjb21tb2RhdGlvbmJhc2U=

