name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push --tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-backend:latest -f backend/Dockerfile .

      - name: Clean up
        run: docker buildx prune -a -f

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push --tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-frontend:latest -f frontend/Dockerfile .

      - name: Clean up
        run: docker buildx prune -a -f

